apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
  namespace: taroky-namespace
spec:
  selector:
    app: frontend-nginx  # must match the label on your nginx pods
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080