apiVersion: v1
kind: Service
metadata:
  name: taroky-nginx
  namespace: taroky-namespace
spec:
  selector:
    app: taroky-nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080