apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-sa
  namespace: taroky-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: taroky-namespace
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  namespace: taroky-namespace
subjects:
  - kind: ServiceAccount
    name: manager-sa
    namespace: taroky-namespace
roleRef:
  kind: Role
  name: manager-role
  apiGroup: rbac.authorization.k8s.io
