apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-server
  template:
    metadata:
      labels:
        app: room-server
    spec:
      containers:
        - name: room-server
          image: yourdockerhub/room-server:latest
          env:
            - name: ROOM_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: room-server
spec:
  selector:
    app: room-server
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
