apiVersion: v1
kind: Service
metadata:
  name: room-198237
spec:
  clusterIP: None
  selector:
    room-id: "198237"
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-198237
spec:
  replicas: 1
  selector:
    matchLabels:
      room-id: "198237"
  template:
    metadata:
      labels:
        room-id: "198237"
    spec:
      containers:
      - name: room
        image: your-dockerhub-username/room:latest
        ports:
        - containerPort: 3000
        env:
        - name: ROOM_ID
          value: "198237"
