apiVersion: v1
kind: Service
metadata:
  name: taroky-server
  namespace: taroky-namespace
spec:
  selector:
    app: taroky-server
  ports:
    - protocol: TCP
      port: 8449      
      targetPort: 8449
  type: ClusterIP     
