apiVersion: v1
kind: Service
metadata:
  name: game-server
  namespace: taroky-namespace
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 8449        # Port exposed by the service
      targetPort: 8449  # Port your game-server container listens on
  type: ClusterIP       # Internal service (default)
