export enum Suit {
  Spade = 0,
  Club = 1,
  Heart = 2,
  Diamond = 3,
  Trump = 4,
}

export const SUIT = {
  0: "Spade",
  1: "Club",
  2: "Heart",
  3: "Diamond",
  4: "Trump",
  SPADE: "Spade",
  CLUB: "Club",
  HEART: "Heart",
  DIAMOND: "Diamond",
  TRUMP: "Trump",
} as const;

export const SUIT_REVERSE: Record<string, Suit> = {
  Spade: Suit.Spade,
  Club: Suit.Club,
  Heart: Suit.Heart,
  Diamond: Suit.Diamond,
  Trump: Suit.Trump,
};

export enum Value {
  ACE = "Ace",
  TWO = "Two",
  THREE = "Three",
  FOUR = "Four",
  SEVEN = "Seven",
  EIGHT = "Eight",
  NINE = "Nine",
  TEN = "Ten",
  JACK = "Jack",
  RIDER = "Rider",
  QUEEN = "Queen",
  KING = "King",
  I = "I",
  II = "II",
  III = "III",
  IIII = "IIII",
  V = "V",
  VI = "VI",
  VII = "VII",
  VIII = "VIII",
  IX = "IX",
  X = "X",
  XI = "XI",
  XII = "XII",
  XIII = "XIII",
  XIV = "XIV",
  XV = "XV",
  XVI = "XVI",
  XVII = "XVII",
  XVIII = "XVIII",
  XIX = "XIX",
  XX = "XX",
  XXI = "XXI",
  SKYZ = "Skyz",
}

export const RED_VALUE = {
  0: "Ace",
  1: "Two",
  2: "Three",
  3: "Four",
  4: "Jack",
  5: "Rider",
  6: "Queen",
  7: "King",
} as const;

export const RED_VALUE_ACE_HIGH = {
  0: "Two",
  1: "Three",
  2: "Four",
  3: "Ace",
  4: "Jack",
  5: "Rider",
  6: "Queen",
  7: "King",
} as const;

export const BLACK_VALUE = {
  0: "Seven",
  1: "Eight",
  2: "Nine",
  3: "Ten",
  4: "Jack",
  5: "Rider",
  6: "Queen",
  7: "King",
} as const;

export const TRUMP_VALUE = {
  0: "I",
  1: "II",
  2: "III",
  3: "IIII",
  4: "V",
  5: "VI",
  6: "VII",
  7: "VIII",
  8: "IX",
  9: "X",
  10: "XI",
  11: "XII",
  12: "XIII",
  13: "XIV",
  14: "XV",
  15: "XVI",
  16: "XVII",
  17: "XVIII",
  18: "XIX",
  19: "XX",
  20: "XXI",
  21: "Skyz",
} as const;

export const VALUE_REVERSE: Record<string, number> = {
  Ace: 0,
  Two: 1,
  Three: 2,
  Four: 3,
  Jack: 4,
  Rider: 5,
  Queen: 6,
  King: 7,
  Seven: 0,
  Eight: 1,
  Nine: 2,
  Ten: 3,
  I: 0,
  II: 1,
  III: 2,
  IIII: 3,
  V: 4,
  VI: 5,
  VII: 6,
  VIII: 7,
  IX: 8,
  X: 9,
  XI: 10,
  XII: 11,
  XIII: 12,
  XIV: 13,
  XV: 14,
  XVI: 15,
  XVII: 16,
  XVIII: 17,
  XIX: 18,
  XX: 19,
  XXI: 20,
  Skyz: 21,
};

export const VALUE_REVERSE_ACE_HIGH: Record<string, number> = {
  Two: 0,
  Three: 1,
  Four: 2,
  Ace: 3,
  Jack: 4,
  Rider: 5,
  Queen: 6,
  King: 7,
  Seven: 0,
  Eight: 1,
  Nine: 2,
  Ten: 3,
  I: 0,
  II: 1,
  III: 2,
  IIII: 3,
  V: 4,
  VI: 5,
  VII: 6,
  VIII: 7,
  IX: 8,
  X: 9,
  XI: 10,
  XII: 11,
  XIII: 12,
  XIV: 13,
  XV: 14,
  XVI: 15,
  XVII: 16,
  XVIII: 17,
  XIX: 18,
  XX: 19,
  XXI: 20,
  Skyz: 21,
};

export enum Difficulty {
  BEGINNER = 0,
  EASY = 1,
  NORMAL = 2,
  HARD = 3,
  RUTHLESS = 4,
  AI = 5,
}
export const DIFFICULTY_TABLE = {
  0: "Beginner",
  1: "Easy",
  2: "Normal",
  3: "Hard",
  4: "Ruthless",
  5: "AI",
} as const;

export enum MessageType {
  POVINNOST = 0,
  MONEY_CARDS = 1,
  PARTNER = 2,
  VALAT = 3,
  CONTRA = 4,
  IOTE = 5,
  LEAD = 6,
  PLAY = 7,
  WINNER = 8,
  PREVER_TALON = 9,
  PAY = 10,
  CONNECT = 11,
  DISCONNECT = 12,
  SETTING = 13,
  TRUMP_DISCARD = 14,
  NOTATION = 15,
  DRAW = 16,
  CUT = 17,
}

export enum PlayerType {
  HUMAN = 0,
  ROBOT = 1,
  AI = 2,
}

export const DISCONNECT_TIMEOUT = 20_000 as const;

export const SENSITIVE_ACTIONS: Record<string, boolean> = {
  povinnostBidaUniChoice: true,
  contra: true,
  preverContra: true,
  preverValatContra: true,
  valatContra: true,
  iote: true,
};

export enum RoomType {
  STANDARD = 0,
  DEBUG = 1,
  TRAINING = 2,
  CHALLENGE = 3,
  TEST = 4,
}

export const NUM_AVATARS = 58 as const;

export enum Action {
  START = "start",
  PLAY = "play",
  SHUFFLE = "shuffle",
  CUT = "cut",
  DEAL = "deal",
  CHOICE = "12choice",
  PREVER = "prever",
  DRAW_TALON = "drawTalon",
  PASS_TALON = "passTalon",
  PASS_PREVER = "passPrever",
  CALL_PREVER = "callPrever",
  DISCARD = "discard",
  DRAW_PREVER_TALON = "drawPreverTalon",
  MONEY_CARDS = "moneyCards",
  PARTNER = "partner",
  POVINNOST_BIDA_UNI_CHOICE = "povinnostBidaUniChoice",
  VALAT = "valat",
  LEAD = "lead",
  FOLLOW = "follow",
  IOTE = "iote",
  CONTRA = "contra",
  PREVER_CONTRA = "preverContra",
  PREVER_VALAT_CONTRA = "preverValatContra",
  VALAT_CONTRA = "valatContra",
  WIN_TRICK = "winTrick",
  COUNT_POINTS = "countPoints",
  RESET = "resetBoard",
  RETRY = "retry",
}

export enum ShuffleType {
  CUT = 1,
  RIFFLE = 2,
  RANDOM = 3,
}

export enum CutType {
  CUT = "Cut",
  ONES = "1",
  TWOS = "2",
  THREES = "3",
  FOURS = "4",
  SIXES = "6",
  TWELVES = "12",
  TWELVE_STRAIGHT = "12 Straight",
  THREE_FOUR_FIVE = "345",
}

export enum MoneyCards {
  UNI = "Uni",
  BIDA = "Bida",
  TAROKY = "Taroky",
  TAROCKY = "Tarocky",
  TRUL = "Trul",
  PANE = "Pane",
  ROSA_PANE = "Rosa-Pane",
  ROSA_PANE_PLUS = "Rosa-Pane+",
}
