apiVersion: apps/v1
kind: Deployment
metadata:
  name: taroky-nginx
  namespace: taroky-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taroky-nginx
  template:
    metadata:
      labels:
        app: taroky-nginx
    spec:
      containers:
      - name: nginx
        image: jamesqm1/taroky-nginx:latest
        ports:
        - containerPort: 80

