# server/room-template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-PLACEHOLDER
  namespace: taroky-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-PLACEHOLDER
  template:
    metadata:
      labels:
        app: room-PLACEHOLDER
    spec:
      containers:
        - name: room-server
          image: professorninja/taroky-room:latest
          env:
            - name: ROOM_ID
              value: "room-PLACEHOLDER"
            - name: REDIS_HOST
              value: "redis.taroky-namespace.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: room-PLACEHOLDER
spec:
  selector:
    app: room-PLACEHOLDER
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
